disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - fatal_error_message
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - Tests/DuprKitTests/Mocks.swift  # Allow force try/unwrap in test mocks

# Line length
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true

# File length
file_length:
  warning: 500
  error: 1000

# Function body length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# Identifier names
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - db
    - x
    - y
    - i  # Allow 'i' for loop counters

# Custom rules
custom_rules:
  no_direct_process_info_environment:
    name: "No Direct ProcessInfo Environment Access"
    regex: 'ProcessInfo\.processInfo\.environment'
    message: "Use Environment.get() instead of ProcessInfo.processInfo.environment for better testability and .env file support"
    severity: error
    excluded:
      - "Tests/DuprKitTests/Environment.swift"  # This is the implementation itself
    
  no_print_statements:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    match_kinds:
      - identifier
    message: "Use Logger instead of print for better logging control"
    severity: warning
